version: '3'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: homewiki_db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgres/data/
  adminer:
    image: adminer:4.7-standalone
    ports:
      - 5431:8080
    container_name: homewiki_adminer
    restart: unless-stopped
  wiki:
    image: requarks/wiki:2
    environment:
      DB_HOST: db
      DB_TYPE: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: homewiki_wikijs
    restart: unless-stopped
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


volumes:
  db-data:
